// Package user defines domain types for users.
// Code generated by AitiGo CLI. DO NOT EDIT unless you know what you are doing.
package user

// Repository defines repository behavior for the domain.
type Repository interface {
	// TODO: add methods
}
