// Code generated by AitiGo CLI. DO NOT EDIT unless you know what you are doing.
package user

// UserRepository defines repository behavior for the domain.
type UserRepository interface {
	// TODO: add methods
}
