// Package user defines domain types for users.
// Code generated by AitiGo CLI. DO NOT EDIT unless you know what you are doing.
package user

// Service contains domain use cases.
type Service struct {
	// TODO: inject repositories
}
