// Code generated by AitiGo CLI. DO NOT EDIT unless you know what you are doing.
package user

// Userrepository defines repository behavior for the domain.
type Userrepository interface {
	// TODO: add methods
}
