// Code generated by AitiGo CLI. DO NOT EDIT unless you know what you are doing.
package book

// Bookrepository defines repository behavior for the domain.
type Bookrepository interface {
	// TODO: add methods
}
