// Package book defines domain types for books.
// Code generated by AitiGo CLI. DO NOT EDIT unless you know what you are doing.
package book

// Repository defines repository behavior for the domain.
type Repository interface {
	// TODO: add methods
}
