// Code generated by AitiGo CLI. DO NOT EDIT unless you know what you are doing.
package book

// BookRepository defines repository behavior for the domain.
type BookRepository interface {
	// TODO: add methods
}
