// Package book defines domain types for books.
// Code generated by AitiGo CLI. DO NOT EDIT unless you know what you are doing.
package book

// Service contains domain use cases.
type Service struct {
	// TODO: inject repositories
}
