package cli

import "fmt"

const generatedHeader = "// Code generated by AitiGo CLI. DO NOT EDIT unless you know what you are doing.\n"

func templateEntity(module, name string) string {
	return fmt.Sprintf(`%spackage %s

// %s represents the domain entity.
type %s struct {
	// TODO: add fields
}
`, generatedHeader, module, name, name)
}

func templateRepositoryInterface(module, name string) string {
	return fmt.Sprintf(`%spackage %s

// %s defines repository behavior for the domain.
type %s interface {
	// TODO: add methods
}
`, generatedHeader, module, name, name)
}

func templateService(module, name string) string {
	return fmt.Sprintf(`%spackage %s

// %s contains domain usecases.
type %s struct {
	// TODO: inject repositories
}
`, generatedHeader, module, name, name)
}

func templateController(name, module string) string {
	return fmt.Sprintf(`%s// Module: %s
package controller

// %s handles HTTP for module %q.
type %s struct {
	// TODO: inject domain services
}

// TODO: add handler methods with JSON response format from CONVENTIONS.md
`, generatedHeader, module, name, module, name)
}

func templateRepositoryImpl(name string) string {
	return fmt.Sprintf(`%spackage repository

// %s is an infra implementation of a domain repository.
type %s struct {
	// TODO: add infra dependencies (db, cache, external API)
}
`, generatedHeader, name, name)
}
