// Package controller handles HTTP controllers.
// Code generated by AitiGo CLI. DO NOT EDIT unless you know what you are doing.
// Module: article
package controller

// ArticleController handles HTTP for module "article".
type ArticleController struct {
	// TODO: inject domain services
}

// TODO: add handler methods with JSON response format from CONVENTIONS.md
