// Code generated by AitiGo CLI. DO NOT EDIT unless you know what you are doing.
// Module: book
package controller

// BookController handles HTTP for module "book".
type BookController struct {
	// TODO: inject domain services
}

// TODO: add handler methods with JSON response format from CONVENTIONS.md
