// Code generated by AitiGo CLI. DO NOT EDIT unless you know what you are doing.
// Module: user
package controller

// Usercontroller handles HTTP for module "user".
type Usercontroller struct {
	// TODO: inject domain services
}

// TODO: add handler methods with JSON response format from CONVENTIONS.md
