// Package controller handles HTTP controllers.
// Code generated by AitiGo CLI. DO NOT EDIT unless you know what you are doing.
// Module: user
package controller

// UserController handles HTTP for module "user".
type UserController struct {
	// TODO: inject domain services
}

// TODO: add handler methods with JSON response format from CONVENTIONS.md
