// Code generated by AitiGo CLI. DO NOT EDIT unless you know what you are doing.
package article

// Articlerepository defines repository behavior for the domain.
type Articlerepository interface {
	// TODO: add methods
}
