// Code generated by AitiGo CLI. DO NOT EDIT unless you know what you are doing.
package article

// Articleservice contains domain usecases.
type Articleservice struct {
	// TODO: inject repositories
}
