// Code generated by AitiGo CLI. DO NOT EDIT unless you know what you are doing.
package article

// ArticleRepository defines repository behavior for the domain.
type ArticleRepository interface {
	// TODO: add methods
}
