// Package article defines domain types for articles.
// Code generated by AitiGo CLI. DO NOT EDIT unless you know what you are doing.
package article

// Repository defines repository behavior for the domain.
type Repository interface {
	// TODO: add methods
}
