// Code generated by AitiGo CLI. DO NOT EDIT unless you know what you are doing.
package article

// ArticleService contains domain usecases.
type ArticleService struct {
	// TODO: inject repositories
}
