// Package article defines domain types for articles.
// Code generated by AitiGo CLI. DO NOT EDIT unless you know what you are doing.
package article

// Service contains domain use cases.
type Service struct {
	// TODO: inject repositories
}
