// Code generated by AitiGo CLI. DO NOT EDIT unless you know what you are doing.
package repository

// ArticleRepositoryImpl is an infra implementation of a domain repository.
type ArticleRepositoryImpl struct {
	// TODO: add infra dependencies (db, cache, external API)
}
