// Code generated by AitiGo CLI. DO NOT EDIT unless you know what you are doing.
package repository

// BookrepositoryImpl is an infra implementation of a domain repository.
type BookrepositoryImpl struct {
	// TODO: add infra dependencies (db, cache, external API)
}
