// Package repository provides infra repository implementations.
// Code generated by AitiGo CLI. DO NOT EDIT unless you know what you are doing.
package repository

// BookRepositoryImpl is an infra implementation of a domain repository.
type BookRepositoryImpl struct {
	// TODO: add infra dependencies (db, cache, external API)
}
