// Code generated by AitiGo CLI. DO NOT EDIT unless you know what you are doing.
package repository

// UserrepositoryImpl is an infra implementation of a domain repository.
type UserrepositoryImpl struct {
	// TODO: add infra dependencies (db, cache, external API)
}
